#!/bin/bash

# Runs all the koat test files in this and every subdirectory.
# The results are put into *.output files.
# The build takes about 40 minutes on Intel-hyperthreaded 8 cores.
# The GNU tool parallel need to be installed.
# `sudo apt-get install parallel`
# The timeout stops single tests after x seconds.
find . -name "*.output" -type f -delete
find . -name "*.koat" | parallel -j+0 --eta --timeout 180 'koat2 analyse -i {} -r all --cfr &> {.}.output'
sleep 1m
./view_results &> 20200217_results_cfr
./view_times &> 20200217_times_cfr
./view_costs &> 20200217_costs_cfr
sleep 1m

find . -name "*.output" -type f -delete
find . -name "*.koat" | parallel -j+0 --eta --timeout 180 'koat2 analyse -i {} -r all &> {.}.output'
sleep 1m
./view_results &> 20200217_results
./view_times &> 20200217_times
./view_costs &> 20200217_costs
sleep 1m
find . -name "*.output" -type f -delete
