#!/bin/bash

# Runs all the koat test files in this and every subdirectory.
# The results are put into *.output files.
# The build takes about 40 minutes on Intel-hyperthreaded 8 cores.
# The GNU tool parallel need to be installed.
# `sudo apt-get install parallel`
# The timeout stops single tests after x seconds.
find . -name "*.koatoutput" -type f -delete
find . -name *.koatoutput | parallel -j+0 --eta --timeout 180 'koat2 analyse -i {} -r all &> {.}.output'
