#!/usr/bin/env bash
#
# To enable the formatting hook, copy this file to $REPOSITORY_ROOT/.git/hooks/pre-commit

if ! dune build @fmt; then
  for i in $(seq 1 1 3); do echo; done
  echo Accept changes by running \`dune promote\`
  exit 1
fi

