#!/bin/bash

# Runs all the koat test files in this and every subdirectory.
# The results are put into *.output files.
# The build takes about 40 minutes on Intel-hyperthreaded 8 cores.
# The GNU tool parallel need to be installed.
# `sudo apt-get install parallel`
# The timeout stops single tests after x seconds.
#find . -name "*.output" -type f -delete
#find . -name "*.koat" | parallel -j+0 --eta --timeout 90 'koat2 analyse --preprocessors=reachable,sat,eliminate,invgen -d 5 --twn -i {} -r all &> {.}.output'
#./view_results &> 2021_07_13_results_twn
#./view_times &> 2021_07_13_times_twn
#./view_costs &> 2021_07_13_costs_twn

find . -name "*.output" -type f -delete
find . -name "*.koat" | parallel -j+0 --eta --timeout 90 'koat2 analyse --preprocessors=reachable,sat,eliminate,invgen -d 5 -i {} -r all &> {.}.output'
./view_results &> 2021_07_13_results
./view_times &> 2021_07_13_times
./view_costs &> 2021_07_13_costs
