# This is a basic workflow to help you get started with Actions

name: Run Dockerfile


# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build with Docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=max
  format:
    name: Format with Ocamlformat
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: .github/workflows/ocamlformat/.
          load: true
          tags: ocamlformat:latest
          cache-from: type=gha
          cache-to: type=gha,mode=min
      # We have to work around a weird permission error below, hence sudo.
      # Run the command twice as on promotion of changes `dune build @fmt` returns 1 as exit code
      - run: docker run -v "$(pwd):$(pwd)" -t ocamlformat bash -c "cd $(pwd); sudo dune build @fmt --auto-promote; sudo dune build @fmt --auto-promote"
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ocamlformat
