# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch

# change branch to probabilistic later on
on:
  push:
    branches: [ probabilistic ]
  pull_request:
    branches: [ probabilistic ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - uses: actions/cache@v1
      name: Cache docker image
      with:
        path: ~/cache
        key: ${{ runner.os }}-docker-opam-4.09.1-2

    - name: restore docker cache
      run: |
        if [ -e ~/image.tar.xz ]; then xz -dc ~/cache/image.tar | docker load; fi

    # Build the binary using docker and run all tests
    - name: build and test
      run: |
        docker build . -t koat2build --target koat2_build
        docker build . -t koat2

    - name: export docker cache
      run: |
        # Save all used docker images
        # Export all cached steps if no cache was present
        if [ ! -e ~/cache ]; then
          mkdir ~/cache
          docker save $(docker history koat2build -q | grep -v missing) | xz -T4 -z -1 - > ~/cache/image.tar.xz
        fi
        df -h

    - name: export artifacts
      run: |
        cd ~
        docker container create --name temp koat2build
        docker container cp temp:/home/opam/build/src/main/koat2.opt koat2
        docker container rm temp
        xz -1 -T4 koat2
        ls -lh
        docker save koat2 | xz -T4 -z -1 - > ~/koat2-docker.tar.xz

    - uses: actions/upload-artifact@v2
      with:
        name: static-binary
        path: ~/koat2.xz

    - uses: actions/upload-artifact@v2
      with:
        name: docker-img
        path: ~/koat2-docker.tar.xz

